export const snapshotDate = '2026-09-29';

export const passages = [
  {
    id: 'dn-faq-24680-household-certificate-authority',
    document: 'Hỏi đáp Cổng Thông tin điện tử thành phố Đà Nẵng',
    version: 'Câu trả lời mã 24680, 23/06/2026',
    section: 'Thẩm quyền cấp Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm',
    url: 'https://cttdt.danangportal.gov.vn/web/dng/hoi-dap-public?_HoiDap_WAR_sdthoidapportlet_action=chiTietHoiDapPublic&hoiDapId=24680&p_p_id=HoiDap_WAR_sdthoidapportlet&p_p_lifecycle=0&p_p_mode=view&p_p_state=normal',
    issuedDate: '2026-06-23',
    effectiveDate: null,
    reviewDate: snapshotDate,
    claimTags: ['household-business-authority', 'conditional-route', 'official-next-step'],
    operationTags: ['cafe', 'takeaway', 'food-and-drink', 'drinks-only'],
    excerpt: 'Về thẩm quyền Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm: Căn cứ Quyết định số 76/2026/QĐ-UBND ngày 31/5/2026 của UBND thành phố Đà Nẵng ban hành Quy định phân cấp, phân công, phối hợp về quản lý an toàn thực phẩm trên địa bàn thành phố Đà Nẵng để xác định đơn vị giải quyết thủ tục về cấp giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm; theo đó, việc cấp Giấy chứng nhận cơ sở kinh doanh thực phẩm thuộc thẩm quyền của Sở Y tế (đối với trường hợp tổ chức kinh doanh được cấp Giấy chứng nhận đăng ký doanh nghiệp hoặc Giấy chứng nhận đầu tư hoặc Giấy chứng nhận đăng ký liên hợp tác xã) hoặc thẩm quyền của UBND cấp xã (đối với trường hợp tổ chức, cá nhân có Giấy chứng đăng ký hộ kinh doanh hoặc Giấy chứng nhận đăng ký hợp tác xã).',
    useLimits: 'Câu trả lời là nguồn địa phương về phân công đầu mối theo loại giấy đăng ký; không xác nhận cơ sở cụ thể có phải xin giấy hay bộ hồ sơ hiện hành. Câu hỏi gốc nói về thịt chim bồ câu, không phải quán cà phê.',
  },
  {
    id: 'dn-procedure-1-013855-h17',
    document: 'Danh mục thủ tục hành chính cấp xã Đà Nẵng, Quyết định 1234/QĐ-UBND',
    version: 'Danh mục ký ngày 28/08/2025',
    section: 'Lĩnh vực an toàn thực phẩm · mã 1.013855.H17',
    url: 'https://duyxuyen.danang.gov.vn/documents/1640879/1902799/Thu%2Btuc%2Bcap%2Bxa.pdf/4844c89b-5a07-a8c7-7151-e47162541bb8?t=1757389588514',
    issuedDate: '2025-08-28',
    effectiveDate: null,
    reviewDate: snapshotDate,
    claimTags: ['procedure-code', 'official-next-step', 'unverified-administrative-details'],
    operationTags: ['cafe', 'takeaway', 'food-and-drink', 'drinks-only'],
    excerpt: 'Tên thủ tục hành chính: Cấp giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm đối với cơ sở kinh doanh dịch vụ ăn uống, cơ sở sản xuất thực phẩm thuộc phạm vi quản lý của Bộ Y tế. Mã số thủ tục hành chính: 1.013855.H17 (TTHC phân cấp cho UBND cấp xã thực hiện).',
    useLimits: 'Danh mục năm 2025 chỉ giúp nhận diện mã thủ tục và nội dung phân cấp trong danh mục đó. Không dùng để khẳng định thành phần hồ sơ, lệ phí, thời hạn hoặc quy trình hiện hành.',
  },
  {
    id: 'vn-decree-15-2018-articles-11-12',
    document: 'Nghị định 15/2018/NĐ-CP của Chính phủ',
    version: 'Nghị định số 15/2018/NĐ-CP, ban hành và có hiệu lực 02/02/2018',
    section: 'Chương I · Điều 3 khoản 10; Chương V · Điều 11 khoản 1 và Điều 12 khoản 1 điểm d, đ, i',
    url: 'https://vanban.chinhphu.vn/?Pageid=27160&docid=192829',
    documentUrl: 'https://datafiles.chinhphu.vn/cpp/files/vbpq/2018/02/15.signed.pdf',
    issuedDate: '2018-02-02',
    effectiveDate: '2018-02-02',
    reviewDate: snapshotDate,
    claimTags: ['certificate-rule', 'exception-criteria', 'no-size-only-exemption', 'conditions-for-exception'],
    operationTags: ['cafe', 'takeaway', 'food-and-drink', 'drinks-only'],
    excerpt: 'Khoản 10 Điều 3: “Cơ sở kinh doanh thực phẩm nhỏ lẻ là cơ sở do cá nhân, nhóm cá nhân, hộ gia đình thực hiện đăng ký hộ kinh doanh và cơ sở không được cấp Giấy chứng nhận đăng ký kinh doanh hoặc Giấy chứng nhận đăng ký doanh nghiệp hoặc Giấy chứng nhận đầu tư theo quy định của pháp luật.”\n\nĐiều 11 khoản 1: “Cơ sở sản xuất, kinh doanh thực phẩm phải có Giấy chứng nhận cơ sở đủ điều kiện an toàn thực phẩm khi hoạt động, trừ trường hợp quy định tại khoản 1 Điều 12 Nghị định này.”\n\nĐiều 12 khoản 1 điểm d, đ và i liệt kê: “d) Kinh doanh thực phẩm nhỏ lẻ; đ) Kinh doanh thực phẩm bao gói sẵn; i) Kinh doanh thức ăn đường phố.” Khoản 2: “Các cơ sở quy định tại khoản 1 Điều này phải tuân thủ các yêu cầu về điều kiện bảo đảm an toàn thực phẩm tương ứng.”',
    useLimits: 'Điều 3 khoản 10 gắn loại “kinh doanh thực phẩm nhỏ lẻ” với chủ thể và giấy đăng ký, không nêu diện tích hoặc quy mô quán làm căn cứ độc lập. Cần đối chiếu đúng giấy đăng ký và hoạt động thực tế; danh sách ngoại lệ chỉ nói về Giấy chứng nhận, không xóa các điều kiện an toàn thực phẩm tương ứng. Không kết luận miễn giấy khi dữ kiện chưa khớp rõ một loại hình.',
  },
  {
    id: 'vn-law-55-2010-article-29-separate-utensils',
    document: 'Luật 55/2010/QH12 về An toàn thực phẩm',
    version: 'Luật số 55/2010/QH12, thông qua ngày 17/06/2010',
    section: 'Điều 29 khoản 1 · cơ sở chế biến, kinh doanh dịch vụ ăn uống',
    url: 'https://vanban.chinhphu.vn/?docid=96032&pageid=27160',
    issuedDate: '2010-06-17',
    effectiveDate: '2011-07-01',
    reviewDate: snapshotDate,
    claimTags: ['separate-raw-cooked-utensils'],
    operationTags: ['cafe', 'takeaway', 'food-and-drink'],
    excerpt: 'Điều 29. Điều kiện bảo đảm an toàn thực phẩm đối với cơ sở chế biến, kinh doanh dịch vụ ăn uống. 1. Có dụng cụ, đồ chứa đựng riêng cho thực phẩm sống và thực phẩm chín.',
    useLimits: 'Đây là một điều kiện trong số nhiều điều kiện; việc đánh dấu đã chuẩn bị không xác nhận quán đáp ứng pháp luật.',
  },
  {
    id: 'vn-law-55-2010-article-29-safe-utensils',
    document: 'Luật 55/2010/QH12 về An toàn thực phẩm',
    version: 'Luật số 55/2010/QH12, thông qua ngày 17/06/2010',
    section: 'Điều 29 khoản 2–3 · dụng cụ chế biến và ăn uống',
    url: 'https://vanban.chinhphu.vn/?docid=96032&pageid=27160',
    issuedDate: '2010-06-17',
    effectiveDate: '2011-07-01',
    reviewDate: snapshotDate,
    claimTags: ['safe-cooking-utensils', 'clean-dry-serving-utensils'],
    operationTags: ['cafe', 'takeaway', 'food-and-drink', 'drinks-only'],
    excerpt: '2. Dụng cụ nấu nướng, chế biến phải bảo đảm an toàn vệ sinh. 3. Dụng cụ ăn uống phải được làm bằng vật liệu an toàn, rửa sạch, giữ khô.',
    useLimits: 'Đây là các điều kiện pháp luật; người dùng chỉ tự rà soát, không tự chứng nhận việc đáp ứng.',
  },
];
